# Generated by Django 4.2.6 on 2023-12-07 23:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('winner', models.CharField(max_length=1)),
                ('squares', models.CharField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
